QuickAnswer/QuickAnswer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('post/<int:pk>/likes/<int:preference>/', views.postPreferenceToggle, name='postpreferencetoggle'),
    path('solution/<int:pk>/likes/<int:preference>/', views.solutionPreferenceToggle, name='solutionpreferencetoggle'),
    path('feedback/',include('feedback.urls')),
    path('user/',include('user.urls',namespace='user')),
    path('post/',include('querysolution.urls',namespace='post')),
	path('account/',include('account.urls',namespace='account')),
    path('search/',views.autocomplete,name="autocomplete"),
    path('searchquery/',views.search,name="search"),
	path('',views.HomePage.as_view(),name="home"),
    path('account/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),


] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuickAnswer/account/urls.py
from django.urls import path,include,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name="account"


urlpatterns=[

	path('login/',auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout'),
	path('signup/',views.SignUp.as_view(template_name='account/signup.html'),name='signup'),
	
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html',
    						                                   	email_template_name='account/password_reset_email.html'),
    															name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
    															name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'), 
    															name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), 
    															name='password_reset_complete'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html',success_url=reverse_lazy('login')), 
                                                                name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), 
    #                                                             name='password_change_done'),
]

QuickAnswer/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name="user"


urlpatterns=[
	 path('profile/edit/', views.editprofile, name="editprofile")
]

QuickAnswer/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
	picture=models.ImageField(upload_to='profile_pics',blank=True)
	about=models.CharField(max_length=50)

	def __str__(self):
		return str(self.user)

QuickAnswer/user/forms.py
from django import forms
from .models import *


class UserProfileForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model =  UserProfile
        fields = ('picture','about')

        widgets={
			'about':forms.Textarea(attrs={
								'placeholder':'Type Something About You',
								'rows':3}),
		}

QuickAnswer/user/views.py
from django.shortcuts import render
from .forms import UserProfileForm
from .models import UserProfile
# Create your views here.

def editprofile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        ins=UserProfile.objects.filter(user=request.user)
        if ins:
            ins.delete()

        if form.is_valid():
        	form.instance.user = request.user
        	form.save()
        	return render(request, 'user/editprofile.html', {'form': form})
    else:
        form = UserProfileForm()
    return render(request, 'user/editprofile.html', {'form': form})

QuickAnswer/user/templates/user/editprofile.html
{% extends 'user/userprofilebase.html' %}
{% load bootstrap4 %}
{% block title %}Edit Profile{% endblock %}
{% block edit %}
<br>	
<div style='width: 60%;margin: 0 auto;padding-top: 2%;'>
<center class="title">Edit Profile</center>
<br>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
   {% bootstrap_form form %}
   <br>
   <center>
  <button type="submit" class="btn btn-outline-primary">Save Changes</button>
  </center>
</form>

</div>
{% endblock %}

QuickAnswer/user/templates/user/userprofilebase.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">

<div class="row">
	<div class="col-5" style="background-color: #c0c0c0;padding: 20px;	border-radius:75% 75% 0 0;">
		<center>
			{% if request.user.profile.picture %}
		  		
		  		<img src="{{request.user.profile.picture.url}}" alt="Profile Picture" width="230px" height="230px" class="rounded-circle shadow p-1 mb-5 bg-white rounded">
			{% else %}
				<img src="{% static 'images/anonymous_user.jpg'%}" alt="Profile Picture" width="230px" height="230px" class="rounded-circle shadow p-1 mb-5 bg-white rounded">
			{% endif %}
		<div >
			{% if request.user.profile.about %}
		  		<p >{{request.user.profile.about}}</p>
			{% else %}
				<p >Click on Edit Profile button and tell us something about you...</p>
			{% endif %}
		</div>
		<p class="title">{{request.user.username}}</p>
		<div class="btn-group" role="group" aria-label="Basic example">
			<a href="{% url 'user:editprofile' %}" class="btn btn-warning" width="50px"> Edit Profile </a>
			<a href="{% url 'account:password_change' %}"" class="btn btn-warning" width="50px">Change Password</a>
		</div>
		</center>

	</div>
	<div class="col-7">
		{% block edit %}

		{% endblock %}
	
	</div>
</div>
</div>
{% endblock %}